### ISSUE TITLE
FM-I3: May linksets be embedded in the other data or must they be independant resources

### ISSUE THREAD

**Issue by JervenBolleman** [FAIRMetrics/Metrics#13]
e.g. UniProt links to hundreds of resources but these links are not collected in separate files or identified by an independent resource. Is it ok, that the linksets are embedded in the dataset itself.

**Comment by micheldumontier** [comment]
no.

**Comment by JervenBolleman** [comment]
@micheldumontier so to be sure I understand your terse answer linksets must have their own identifier.

**Comment by micheldumontier** [comment]
correct!

**Comment by markwilkinson** [comment]
The questionnaire that I created for manual testing assumes that the linksets are separate from the data itself.  In the questionnaire, it is possible to just type-in the linkset, but for an automated evaluation it would need to be a resolvable IRI.  ...though that IRI might generate the linkset dynamically... and it doesn't have to be comprehensive, it only needs to demonstrate that links to external resources DO EXIST in order to "pass" that Metric

**Comment by markwilkinson** [comment]
I'm going to close this issue, if that's OK with you two?
