### ISSUE TITLE
21.XXXX handle prefix is not recognized

### ISSUE THREAD

**Issue by JonathanMELIUS** [FAIRMetrics/Metrics#58]
For example:
[20.1000/5555](http://hdl.handle.net/api/handles/20.1000/5555 )
returns
```
@id": "http://linkeddata.systems//cgi-bin/FAIR_Tests/gen2_unique_identifier#20.1000/5555/result-2019-11-01T13:06:36+00:00",
    "http://schema.org/comment": [
      {
        "@value": "SUCCESS: Found an identifier of type 'handle1'",
        "@language": "en"
      }
    ],
```
But:
[21.12109/P000000001C000000001](http://hdl.handle.net/api/handles/21.12109/P000000001C000000001)
returns
```
"@id": "http://linkeddata.systems//cgi-bin/FAIR_Tests/gen2_unique_identifier#21.12109/P000000001C000000001/result-2019-11-01T13:02:05+00:00",
    "http://schema.org/comment": [
      {
        "@value": "FAILURE: the identifier 21.12109/P000000001C000000001 did not match any known identification system (tested inchi, doi, handle, uri) and therefore did not pass this metric.  If you think this is an error, please contact the FAIR Metrics group (http://fairmetrics.org).",
        "@language": "en"
      }
    ],
```

Looking at the handle1 regex at https://github.com/FAIRMetrics/Metrics/blob/4a770ffca1e658666f60bd0c22ae7cf4bbc62e4e/MetricsEvaluatorCode/Ruby/metrictests/fair_metrics_utilities.rb#L93

'handle1' => Regexp.new(/^[2-9]**_0._**\d{4,9}\/[-._;()\/:A-Z0-9]+$/i)
I think because of the 0 it will only match "rounded tens" 20, 30, 40 etc...

^[2-9][0-9]\\.\d{4,9}\/[-._;()\/:A-Z0-9]+$
It could be a solution for the prefix of my test _21.1209_. 
But I'm not sure how it will interfere and/or solve all other cases.

**Comment by markwilkinson** [comment]
fixed using your suggested regex.  Please confirm it's now responding as expected.
Cheers!

**Comment by JonathanMELIUS** [comment]
It works well with prefix that only contains digit. (e.g 21.12109)
Thanks for the update.

But I quickly stumbled on a prefix that also contains an alphabetic character:
[21.T12996/P000000001C000000001](http://hdl.handle.net/api/handles/21.T12996/P000000014C000000003)

In the regex, \d would need to be changed to \w to also handle those cases.
^[2-9][0-9]\.**\w**{4,9}\/[-._;()\/:A-Z0-9]+$

**Comment by markwilkinson** [comment]
Looking at Handle spec - the identifier structure is (frustratingly!) loosely defined.  ~ "Any character except '/' in front of, and after, the '/' prefix/local-id separator.  This will match a lot of URI structures (luckily, not URLs, but other kinds of URI will certainly pass that description!)

I may have to update the code so that it requires a handle: prefix in cases where you are submitting a Handle :-(  (in cases where the Handle is discovered automatically, I guess we just have to hope for the best!)

I have updated the regex to match that description:  /^[^\/]+\/[^\/]+$/i

That should get you through the end of your day :-)

Cheers!
